version: '3.8'

services:
  keycloak_db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - clearya-net

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    restart: unless-stopped
    networks:
      - clearya-net

  app-db:
    image: postgres:15
    container_name: app-db
    environment:
      POSTGRES_DB: clearyadb
      POSTGRES_USER: clearya
      POSTGRES_PASSWORD: clearya_password
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    networks:
      - clearya-net

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://clearya:clearya_password@app-db:5432/clearyadb

      KEYCLOAK_URL: http://keycloak:8080
      SESSION_SECRET: super_secret_key
      PORT: 5000
    depends_on:
      - keycloak
      - keycloak_db
      - app-db
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - clearya-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      VITE_API_URL: "http://backend:5000"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - clearya-net

volumes:
  keycloak_db-data:
  app-db-data:

networks:
  clearya-net:
    driver: bridge

